/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Administrator/Desktop/Verilog/m34/cpuPLL/cpu_pll.v
 ** Date	:	2017 12 09
 ** TD version	:	3.2.568
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             25.000Mhz
//	Clock multiplication factor: 2
//	Clock division factor:       5
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C1        	| 10.000 MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module cpu_pll(refclk,
		reset,
		stdby,
		extlock,
		clk1_out);

	input refclk;
	input reset;
	input stdby;
	output extlock;
	output clk1_out;

	wire clk1_buf;

	EG_LOGIC_BUFG bufg_feedback( .i(clk1_buf), .o(clk1_out) );

	EG_PHY_PLL #(.DYNCFG("DISABLE"),
		.FIN("25.000"),
		.FEEDBK_PATH("CLKC1_EXT"),
		.STDBY_ENABLE("ENABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("ENABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN(6),
		.ICP_CURRENT(3),
		.KVCO(6),
		.LPF_CAPACITOR(3),
		.LPF_RESISTOR(2),
		.REFCLK_DIV(5),
		.FBCLK_DIV(2),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(100),
		.CLKC1_CPHASE(100),
		.CLKC1_FPHASE(0)	)
	pll_inst (.refclk(refclk),
		.reset(reset),
		.stdby(stdby),
		.extlock(extlock),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(1'b0),
		.dcs(1'b0),
		.dwe(1'b0),
		.di(8'b00000000),
		.daddr(6'b000000),
		.do({open, open, open, open, open, open, open, open}),
		.fbclk(clk1_out),
		.clkc({open, open, open, clk1_buf, open}));

endmodule
