/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Administrator/Desktop/Verilog/m34/ram/ram.v
 ** Date	:	2017 12 11
 ** TD version	:	3.2.568
\************************************************************/

`timescale 1ns / 1ps

module ramm ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 32; 
	parameter ADDR_WIDTH_W = 4;
	parameter DATA_DEPTH_W = 12;
	parameter DATA_WIDTH_R = 32;
	parameter ADDR_WIDTH_R = 4;
	parameter DATA_DEPTH_R = 12;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	EG_LOGIC_DRAM #(
 			.INIT_FILE("ram.MIF"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule